name: Custom build and publish

on:
  workflow_dispatch:

jobs:
  build:
    name: "Custom build and publish release container"
    runs-on: ubuntu-20.04
    if: github.repository == 'hpcc-systems/HPCC-Platform'
    steps:
      - name: vars
        id: vars
        run: |
          echo "::set-output name=date::$(date +'%Y-%m-%d')"
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        uses: ./dockerfiles
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          build_ver: ${{BUILD_BRANCH}}
          build_label: "${{BUILD_BRANCH}}-${{ steps.vars.outputs.date }}"
